require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  DisabledByDefault: true

RSpec/ExampleWording:
  Enabled: true

RSpec/BeEq:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Metrics/AbcSize:
  Enabled: true

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 5

Metrics/ParameterLists:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: true
